git:
  depth: 3

env:
  global:
  - DOCKERHUB_ORG="gospatial"
  - DOCKERHUB_REPO="atlante"
  # DOCKER_USER
  - secure: biokdQm0a7hUdFg8tCwWDbZl+Gv+WglgpZyFEmmZy3UfARij/zBYlha4yCy1NiIYQHABzmhEiISQJDD2pykQQ32Vrynt2RJ+g1yvqwl67vzxTLTsXjBfyfCH/FXAUf9DAdk0QXKrFznpvEoTyBbgsGIRbrID8uIaxFyXjtSy7pK5Z9eGmfBmhTkS8MG6lnNzDwQcJ0kEjZCxfdWqdS6xeJA/WbxtxEaWWYsUfnik1yjGelVF6uRM5VJST3DW7zsMg1c7ekShxxcGGry/N3iPk9wIVeGL6fpe4WqS72P8K8UXzxUGEolpGFf+WDRnWOVEcqauyh2GV9+xGwccL18vMXs0FujC7fWKPpdWVb1IFGibKXglowv7WAUdJfowP0+fNB9Oq/SGuxjClYgFDmAL2yph9Jor3f37nxu9SLb4FFOiUyoTTlVB135NpaqSRpa0/qJjRzPxwE41PJ4ZZR5kxet9WF18MdkEq2ohUakb7HHeXpzDNDL3Zv7TFfgKtF5sgOKdmHHrahuvR2W4VNYaXMy6dMxkj2v9QpXPJO+EtQp5DioI7evbyBZnDIcpGAJbNdBewt4i6He2DJPGhHKZo9vnW3ntkwlWH3A2k/yxtWZxOEclt0qEA8rTKO+gP/YmO0sY7GfSwwIVTQK6BqhQeq/UMHp0HIuDJ/8kIwbokHI=
  # DOCKER_PASSWORD
  - secure: lYp3ZsT65ket2ihCY6G94IDd4ZR6yyunFUI6/90crMZxlqdxERxpr8a1w5B4f9bghRAA0Ck1htCpMRqddgH75yfleHoHZal93jsmfwgsT/aNVoa9hM64cfHYygZTCHMXdbXKbSGSoGR/Ss5sx7hDC38FaeomDT3XdU8WDI+7wCkQy/6W6D0Abtre77cvooNob6SdHQE+Rac74yFwsdGO0o0KRi0fWvFw4gmJzugQyAf37kDBwMJu9PoTYVwfpw0wI02LIl1IuRSZoHCWJ/M+uFZnuclhiIrjTMCizsVl8fyNvwhust7KuQnpGCf8y2G2Fn6jMOsiohjjxSH83iIOPDHexklIp/lHiR0mlebJkkVlbN0h0umTetLAbhfJkFqE2VcCvR0RUmZ076Q1jNvTc01qbCkhCFmGbN5YPC0xe4tphmcdGaObFS5C1beLkC4XI88RCgIQxk+11KE9bCz0HeAD/1FZahOl8i/OUisVgHepUODR9RYScWzHd5pXVyCpCHzWLV9/yhsRKyLYFqKeRm3tXtt8XG3GiH5VS52iuS8AWpbAe4ubOuS7roHA8+lEWWR+rtJq6aE1FOo7gbIxJBMmskfB2key6xAkX+vuYck5KYhnacCEZxOHPVYIMnsVju1J/GMz5klo+U2hj1ivuwsRKY/FacvaoSGRndjyFjg=

jobs:
  include:
    - stage: deploy_docker
      script:
        - git lfs pull
        - docker build -f docker/Dockerfile -t ${DOCKERHUB_ORG}/${DOCKERHUB_REPO} .
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
        - docker push ${DOCKERHUB_ORG}/${DOCKERHUB_REPO}:latest


stages:
  - name: deploy_docker
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master AND NOT (type = pull_request)

services:
- docker
