FROM centos:latest

USER root

RUN yum -y update
RUN yum install -y mesa-libOSMesa.x86_64 libpng libjpeg-turbo librsvg2

# Install Fonts needed by the system
COPY docker/files/fonts/* /usr/share/fonts/default/TrueType/
RUN fc-cache

