FROM golang:latest

RUN apt-get update


RUN apt-get install -y libcairo-dev librsvg2-dev
# deps for building rsvg
RUN apt-get install -y libgdk-pixbuf2.0-dev \
	libpango1.0-dev \
	libxml2-dev \
	libcroco3-dev \
	gtk+-3.0

