// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grid.proto

package grids

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HEMIType int32

const (
	HEMIType_NORTH HEMIType = 0
	HEMIType_SOUTH HEMIType = 1
)

var HEMIType_name = map[int32]string{
	0: "NORTH",
	1: "SOUTH",
}

var HEMIType_value = map[string]int32{
	"NORTH": 0,
	"SOUTH": 1,
}

func (x HEMIType) String() string {
	return proto.EnumName(HEMIType_name, int32(x))
}

func (HEMIType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{0}
}

type MDGID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Part                 uint32   `protobuf:"varint,2,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MDGID) Reset()         { *m = MDGID{} }
func (m *MDGID) String() string { return proto.CompactTextString(m) }
func (*MDGID) ProtoMessage()    {}
func (*MDGID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{0}
}

func (m *MDGID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MDGID.Unmarshal(m, b)
}
func (m *MDGID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MDGID.Marshal(b, m, deterministic)
}
func (m *MDGID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MDGID.Merge(m, src)
}
func (m *MDGID) XXX_Size() int {
	return xxx_messageInfo_MDGID.Size(m)
}
func (m *MDGID) XXX_DiscardUnknown() {
	xxx_messageInfo_MDGID.DiscardUnknown(m)
}

var xxx_messageInfo_MDGID proto.InternalMessageInfo

func (m *MDGID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MDGID) GetPart() uint32 {
	if m != nil {
		return m.Part
	}
	return 0
}

type EditInfo struct {
	By                   string               `protobuf:"bytes,1,opt,name=by,proto3" json:"by,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EditInfo) Reset()         { *m = EditInfo{} }
func (m *EditInfo) String() string { return proto.CompactTextString(m) }
func (*EditInfo) ProtoMessage()    {}
func (*EditInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{1}
}

func (m *EditInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInfo.Unmarshal(m, b)
}
func (m *EditInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInfo.Marshal(b, m, deterministic)
}
func (m *EditInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInfo.Merge(m, src)
}
func (m *EditInfo) XXX_Size() int {
	return xxx_messageInfo_EditInfo.Size(m)
}
func (m *EditInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EditInfo proto.InternalMessageInfo

func (m *EditInfo) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

func (m *EditInfo) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type UTMInfo struct {
	Zone uint32 `protobuf:"varint,1,opt,name=zone,proto3" json:"zone,omitempty"`
	// should be formated at 01; 01-60
	Hemi                 HEMIType `protobuf:"varint,2,opt,name=hemi,proto3,enum=atlante.grids.HEMIType" json:"hemi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UTMInfo) Reset()         { *m = UTMInfo{} }
func (m *UTMInfo) String() string { return proto.CompactTextString(m) }
func (*UTMInfo) ProtoMessage()    {}
func (*UTMInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{2}
}

func (m *UTMInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UTMInfo.Unmarshal(m, b)
}
func (m *UTMInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UTMInfo.Marshal(b, m, deterministic)
}
func (m *UTMInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UTMInfo.Merge(m, src)
}
func (m *UTMInfo) XXX_Size() int {
	return xxx_messageInfo_UTMInfo.Size(m)
}
func (m *UTMInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UTMInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UTMInfo proto.InternalMessageInfo

func (m *UTMInfo) GetZone() uint32 {
	if m != nil {
		return m.Zone
	}
	return 0
}

func (m *UTMInfo) GetHemi() HEMIType {
	if m != nil {
		return m.Hemi
	}
	return HEMIType_NORTH
}

type Grid struct {
	Mdgid                *MDGID               `protobuf:"bytes,1,opt,name=mdgid,proto3" json:"mdgid,omitempty"`
	Sw                   *Grid_LatLng         `protobuf:"bytes,2,opt,name=sw,proto3" json:"sw,omitempty"`
	Ne                   *Grid_LatLng         `protobuf:"bytes,3,opt,name=ne,proto3" json:"ne,omitempty"`
	Len                  *Grid_LatLng         `protobuf:"bytes,4,opt,name=len,proto3" json:"len,omitempty"`
	Country              string               `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	City                 string               `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Utm                  *UTMInfo             `protobuf:"bytes,7,opt,name=utm,proto3" json:"utm,omitempty"`
	Edited               *EditInfo            `protobuf:"bytes,8,opt,name=edited,proto3" json:"edited,omitempty"`
	PublishedAt          *timestamp.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	MetaData             map[string]string    `protobuf:"bytes,11,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Nrn                  string               `protobuf:"bytes,12,opt,name=nrn,proto3" json:"nrn,omitempty"`
	Sheet                string               `protobuf:"bytes,13,opt,name=sheet,proto3" json:"sheet,omitempty"`
	Series               string               `protobuf:"bytes,14,opt,name=series,proto3" json:"series,omitempty"`
	SwDms                *Grid_LatLngDMS      `protobuf:"bytes,15,opt,name=sw_dms,json=swDms,proto3" json:"sw_dms,omitempty"`
	NeDms                *Grid_LatLngDMS      `protobuf:"bytes,16,opt,name=ne_dms,json=neDms,proto3" json:"ne_dms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Grid) Reset()         { *m = Grid{} }
func (m *Grid) String() string { return proto.CompactTextString(m) }
func (*Grid) ProtoMessage()    {}
func (*Grid) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{3}
}

func (m *Grid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid.Unmarshal(m, b)
}
func (m *Grid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid.Marshal(b, m, deterministic)
}
func (m *Grid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid.Merge(m, src)
}
func (m *Grid) XXX_Size() int {
	return xxx_messageInfo_Grid.Size(m)
}
func (m *Grid) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid.DiscardUnknown(m)
}

var xxx_messageInfo_Grid proto.InternalMessageInfo

func (m *Grid) GetMdgid() *MDGID {
	if m != nil {
		return m.Mdgid
	}
	return nil
}

func (m *Grid) GetSw() *Grid_LatLng {
	if m != nil {
		return m.Sw
	}
	return nil
}

func (m *Grid) GetNe() *Grid_LatLng {
	if m != nil {
		return m.Ne
	}
	return nil
}

func (m *Grid) GetLen() *Grid_LatLng {
	if m != nil {
		return m.Len
	}
	return nil
}

func (m *Grid) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Grid) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Grid) GetUtm() *UTMInfo {
	if m != nil {
		return m.Utm
	}
	return nil
}

func (m *Grid) GetEdited() *EditInfo {
	if m != nil {
		return m.Edited
	}
	return nil
}

func (m *Grid) GetPublishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *Grid) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *Grid) GetNrn() string {
	if m != nil {
		return m.Nrn
	}
	return ""
}

func (m *Grid) GetSheet() string {
	if m != nil {
		return m.Sheet
	}
	return ""
}

func (m *Grid) GetSeries() string {
	if m != nil {
		return m.Series
	}
	return ""
}

func (m *Grid) GetSwDms() *Grid_LatLngDMS {
	if m != nil {
		return m.SwDms
	}
	return nil
}

func (m *Grid) GetNeDms() *Grid_LatLngDMS {
	if m != nil {
		return m.NeDms
	}
	return nil
}

type Grid_LatLng struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grid_LatLng) Reset()         { *m = Grid_LatLng{} }
func (m *Grid_LatLng) String() string { return proto.CompactTextString(m) }
func (*Grid_LatLng) ProtoMessage()    {}
func (*Grid_LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{3, 0}
}

func (m *Grid_LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid_LatLng.Unmarshal(m, b)
}
func (m *Grid_LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid_LatLng.Marshal(b, m, deterministic)
}
func (m *Grid_LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid_LatLng.Merge(m, src)
}
func (m *Grid_LatLng) XXX_Size() int {
	return xxx_messageInfo_Grid_LatLng.Size(m)
}
func (m *Grid_LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_Grid_LatLng proto.InternalMessageInfo

func (m *Grid_LatLng) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Grid_LatLng) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Grid_LatLngDMS struct {
	Lat                  string   `protobuf:"bytes,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  string   `protobuf:"bytes,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Grid_LatLngDMS) Reset()         { *m = Grid_LatLngDMS{} }
func (m *Grid_LatLngDMS) String() string { return proto.CompactTextString(m) }
func (*Grid_LatLngDMS) ProtoMessage()    {}
func (*Grid_LatLngDMS) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cc83cc4e6de7d1a, []int{3, 1}
}

func (m *Grid_LatLngDMS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grid_LatLngDMS.Unmarshal(m, b)
}
func (m *Grid_LatLngDMS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grid_LatLngDMS.Marshal(b, m, deterministic)
}
func (m *Grid_LatLngDMS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grid_LatLngDMS.Merge(m, src)
}
func (m *Grid_LatLngDMS) XXX_Size() int {
	return xxx_messageInfo_Grid_LatLngDMS.Size(m)
}
func (m *Grid_LatLngDMS) XXX_DiscardUnknown() {
	xxx_messageInfo_Grid_LatLngDMS.DiscardUnknown(m)
}

var xxx_messageInfo_Grid_LatLngDMS proto.InternalMessageInfo

func (m *Grid_LatLngDMS) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *Grid_LatLngDMS) GetLng() string {
	if m != nil {
		return m.Lng
	}
	return ""
}

func init() {
	proto.RegisterEnum("atlante.grids.HEMIType", HEMIType_name, HEMIType_value)
	proto.RegisterType((*MDGID)(nil), "atlante.grids.MDGID")
	proto.RegisterType((*EditInfo)(nil), "atlante.grids.EditInfo")
	proto.RegisterType((*UTMInfo)(nil), "atlante.grids.UTMInfo")
	proto.RegisterType((*Grid)(nil), "atlante.grids.Grid")
	proto.RegisterMapType((map[string]string)(nil), "atlante.grids.Grid.MetaDataEntry")
	proto.RegisterType((*Grid_LatLng)(nil), "atlante.grids.Grid.LatLng")
	proto.RegisterType((*Grid_LatLngDMS)(nil), "atlante.grids.Grid.LatLngDMS")
}

func init() { proto.RegisterFile("grid.proto", fileDescriptor_5cc83cc4e6de7d1a) }

var fileDescriptor_5cc83cc4e6de7d1a = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x69, 0xda, 0x66, 0xed, 0x75, 0x1d, 0x95, 0x35, 0x0d, 0xab, 0x12, 0xa2, 0xf4, 0xa9,
	0xda, 0x46, 0x82, 0x0a, 0x0f, 0x08, 0x04, 0x12, 0xa8, 0xd3, 0x7e, 0x68, 0x65, 0x52, 0xd6, 0xbd,
	0xf0, 0x32, 0xb9, 0x8b, 0x97, 0x5a, 0x4b, 0x9c, 0x28, 0xbe, 0x52, 0x95, 0xbf, 0x80, 0x3f, 0x1b,
	0xf9, 0x92, 0x4c, 0x6c, 0x80, 0xca, 0xdb, 0xdd, 0xe5, 0xf3, 0x3d, 0xfb, 0xbe, 0x17, 0x03, 0x44,
	0xb9, 0x0a, 0xbd, 0x2c, 0x4f, 0x31, 0x65, 0x5d, 0x81, 0xb1, 0xd0, 0x28, 0x3d, 0x5b, 0x33, 0xfd,
	0x17, 0x51, 0x9a, 0x46, 0xb1, 0xf4, 0xe9, 0xe3, 0x7c, 0x79, 0xeb, 0xa3, 0x4a, 0xa4, 0x41, 0x91,
	0x64, 0x05, 0x3f, 0x3c, 0x80, 0xe6, 0x74, 0x72, 0x7c, 0x3a, 0x61, 0x3b, 0xe0, 0xa8, 0x90, 0xd7,
	0x06, 0xb5, 0x51, 0x3b, 0x70, 0x54, 0xc8, 0x18, 0x34, 0x32, 0x91, 0x23, 0x77, 0x06, 0xb5, 0x51,
	0x37, 0xa0, 0x78, 0x78, 0x06, 0xad, 0xa3, 0x50, 0xe1, 0xa9, 0xbe, 0x4d, 0x2d, 0x3f, 0x5f, 0x57,
	0xfc, 0x7c, 0xcd, 0x3c, 0x68, 0x84, 0x02, 0x25, 0xf1, 0x9d, 0x71, 0xdf, 0x2b, 0x0e, 0xf6, 0xaa,
	0x83, 0xbd, 0x59, 0x75, 0x70, 0x40, 0xdc, 0xf0, 0x0c, 0xb6, 0xae, 0x66, 0x53, 0x6a, 0xc5, 0xa0,
	0xf1, 0x23, 0xd5, 0x92, 0x9a, 0x75, 0x03, 0x8a, 0xd9, 0x01, 0x34, 0x16, 0x32, 0x51, 0xd4, 0x6e,
	0x67, 0xfc, 0xcc, 0x7b, 0x30, 0x96, 0x77, 0x72, 0x34, 0x3d, 0x9d, 0xad, 0x33, 0x19, 0x10, 0x34,
	0xfc, 0xe9, 0x42, 0xe3, 0x38, 0x57, 0x21, 0xdb, 0x87, 0x66, 0x12, 0x46, 0xe5, 0x1c, 0x9d, 0xf1,
	0xee, 0x23, 0x19, 0x4d, 0x1a, 0x14, 0x08, 0xdb, 0x07, 0xc7, 0xac, 0xee, 0xaf, 0xfb, 0x10, 0xb4,
	0xcd, 0xbc, 0x73, 0x81, 0xe7, 0x3a, 0x0a, 0x1c, 0xb3, 0xb2, 0xac, 0x96, 0xbc, 0xbe, 0x99, 0xd5,
	0x92, 0x1d, 0x42, 0x3d, 0x96, 0x9a, 0x37, 0x36, 0xc2, 0x16, 0x63, 0x1c, 0xb6, 0x6e, 0xd2, 0xa5,
	0xc6, 0x7c, 0xcd, 0x9b, 0xe4, 0x65, 0x95, 0x5a, 0x57, 0x6e, 0x14, 0xae, 0xb9, 0x4b, 0x65, 0x8a,
	0xd9, 0x08, 0xea, 0x4b, 0x4c, 0xf8, 0x16, 0xf5, 0xde, 0x7b, 0xd4, 0xbb, 0xb4, 0x33, 0xb0, 0x08,
	0xf3, 0xc1, 0x95, 0xa1, 0x42, 0x19, 0xf2, 0x16, 0xc1, 0x8f, 0x1d, 0xac, 0xf6, 0x18, 0x94, 0x18,
	0xfb, 0x08, 0xdb, 0xd9, 0x72, 0x1e, 0x2b, 0xb3, 0x90, 0xe1, 0xb5, 0x40, 0x0e, 0x1b, 0xf7, 0xd8,
	0xb9, 0xe7, 0x3f, 0x23, 0xfb, 0x04, 0xed, 0x44, 0xa2, 0xb8, 0x0e, 0x05, 0x0a, 0xde, 0x19, 0xd4,
	0x47, 0x9d, 0xf1, 0xcb, 0xbf, 0xcd, 0x3e, 0x95, 0x28, 0x26, 0x02, 0xc5, 0x91, 0x9d, 0x31, 0x68,
	0x25, 0x65, 0xca, 0x7a, 0x50, 0xd7, 0xb9, 0xe6, 0xdb, 0x34, 0xac, 0x0d, 0xd9, 0x2e, 0x34, 0xcd,
	0x42, 0x4a, 0xe4, 0x5d, 0xaa, 0x15, 0x09, 0xdb, 0x03, 0xd7, 0xc8, 0x5c, 0x49, 0xc3, 0x77, 0xa8,
	0x5c, 0x66, 0xec, 0x2d, 0xb8, 0x66, 0x75, 0x1d, 0x26, 0x86, 0x3f, 0xa5, 0x8b, 0x3f, 0xff, 0xb7,
	0xf1, 0x93, 0xe9, 0x65, 0xd0, 0x34, 0xab, 0x49, 0x42, 0x2a, 0x2d, 0x49, 0xd5, 0xfb, 0x2f, 0x95,
	0x96, 0x93, 0xc4, 0xf4, 0x0f, 0xc1, 0x2d, 0x6a, 0xf6, 0xd6, 0xb1, 0x40, 0xfa, 0xdb, 0x9c, 0xc0,
	0x86, 0x54, 0xd1, 0x11, 0xfd, 0x56, 0xb6, 0xa2, 0xa3, 0xbe, 0x0f, 0xed, 0xfb, 0x0e, 0xbf, 0x0b,
	0xda, 0x7f, 0x08, 0xda, 0x85, 0xe0, 0x03, 0x74, 0x1f, 0xb8, 0x64, 0x91, 0x3b, 0x59, 0xbd, 0x35,
	0x1b, 0x5a, 0x6f, 0xbe, 0x8b, 0x78, 0x29, 0x4b, 0x59, 0x91, 0xbc, 0x77, 0xde, 0xd5, 0xf6, 0x07,
	0xd0, 0xaa, 0x1e, 0x07, 0x6b, 0x43, 0xf3, 0xeb, 0x45, 0x30, 0x3b, 0xe9, 0x3d, 0xb1, 0xe1, 0xe5,
	0xc5, 0xd5, 0xec, 0xa4, 0x57, 0xfb, 0xf2, 0xfa, 0x9b, 0x17, 0x29, 0x5c, 0x2c, 0xe7, 0xde, 0x4d,
	0x9a, 0xf8, 0x51, 0xfa, 0xca, 0x64, 0x02, 0x95, 0x88, 0xfd, 0x44, 0x64, 0x98, 0xa6, 0xf1, 0x9d,
	0x42, 0xbf, 0x74, 0xc1, 0x27, 0x17, 0xe6, 0x2e, 0x2d, 0xff, 0xcd, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0xab, 0x54, 0x74, 0x68, 0x04, 0x00, 0x00,
}
