[[providers]]
	name     = "PostgisDb50k"
	type     = "postgresql"
	host     = "docker.for.mac.localhost"
	database = "50k"
	user     = "gdey"
	password = ""


[[sheets]]
	name          = "50k"
	provider_grid = "PostgisDb50K"
	scale         = 50000
	dpi           = 96
	zoom          = 13.0
	style         = "style/topo.json"
	template      = "templates/50k_template.svg"




