sudo: false
language: node_js
node_js:
  - "4"
  - "6"
before_install:
  - "$CXX --version"
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8