name: On push
on: 
  push:

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go: ['1.14']

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull git large file store (lfs)
      run: git lfs pull

    #- name: Run Go tests
    #  run: go test -v -race ./...
