name: On push
on: 
  push:
    branches: 
      - master

env: 
  DOCKERHUB_ORG: gospatial
  ATLANTE_DOCKERHUB_REPO: atlante
  ATLANTE_INSET_MAPS_DOCKERHUB_REPO: atlante-inset-maps

jobs:
  test:
    name: Test on Ubuntu, build and deploy Docker
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go: ['1.14']

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull git large file store (lfs)
      run: git lfs pull

    #- name: Run Go tests
    #  run: go test -v -race ./...

    - name: Set build number
      run: echo "BUILD_NUMBER=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

    - name: "[atlante] Build Docker container"
      run: docker build -f docker/Dockerfile-atlante -t ${{env.ATLANTE_DOCKERHUB_REPO}} .

    - name: "[atlante] Tag the Docker container"
      run: |
        docker tag ${{env.ATLANTE_DOCKERHUB_REPO}}:latest ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_DOCKERHUB_REPO}}:master-${{env.BUILD_NUMBER}}
        docker tag ${{env.ATLANTE_DOCKERHUB_REPO}}:latest ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_DOCKERHUB_REPO}}:latest

    - name: Login to Docker hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login --username "${{secrets.DOCKER_USER}}" --password-stdin

    - name: "[atlante] Push Docker container to Docker Hub"
      run: |
        docker push ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_DOCKERHUB_REPO}}:master-${{env.BUILD_NUMBER}}
        docker push ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_DOCKERHUB_REPO}}:latest

    - name: "[atlante-inset-maps] Build Docker container"
      run: docker build -f docker/Dockerfile-atlante-inset-maps -t ${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}} .

    - name: "[atlante-inset-maps] Tag the Docker container"
      run: |
        docker tag ${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}}:latest ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}}:master-${{env.BUILD_NUMBER}}
        docker tag ${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}}:latest ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}}:latest

    - name: "[atlante-inset-maps] Push Docker container to Docker Hub"
      run: |
        docker push ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}}:master-${{env.BUILD_NUMBER}}
        docker push ${{env.DOCKERHUB_ORG}}/${{env.ATLANTE_INSET_MAPS_DOCKERHUB_REPO}}:latest
